name: Reusable Dotnet Test

on:
  workflow_call:
    inputs:
      platform:
        description: 'The platform to run the tests on (e.g., ubuntu-latest, windows-latest)'
        required: true
        type: string
      dotnet-version:
        description: 'The version of dotnet to use X.X.X'
        required: true
        type: string
      test-project-path:
        description: 'The path to the test project'
        required: true
        type: string
      use-debug:
        description: 'Run the pipeline with Debug configuration instead of Release'
        required: false
        type: boolean
        default: false

jobs:
  run-tests:
    runs-on: ${{ inputs.platform }}
    env:
      DOTNET_CONFIGURATION: ${{ inputs.use-debug && 'Debug' || 'Release' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Clean
        run: dotnet clean ${{ inputs.test-project-path }} --configuration $${{ env.DOTNET_CONFIGURATION }}

      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.test-project-path }}

      - name: Build
        run: dotnet build ${{ inputs.test-project-path }} --configuration $${{ env.DOTNET_CONFIGURATION }} --no-restore

      - name: Run Unit Tests
        run: dotnet test ${{ inputs.test-project-path }} --configuration $${{ env.DOTNET_CONFIGURATION }}
