name: Reusable Dotnet Test Matrix

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'The version of dotnet to use X.X.X'
        required: true
        type: string
      test-project-path:
        description: 'The path to the test project'
        required: true
        type: string

jobs:
  matrix-test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Call reusable-dotnet-test
        uses: dusrdev/actions/.github/workflows/reusable-dotnet-test.yaml
        with:
          platform: ${{ matrix.platform }}
          dotnet-version: ${{ inputs.dotnet-version }}
          configuration: ${{ matrix.configuration }}
          test-project-path: ${{ inputs.test-project-path }}