name: Reusable Dotnet Test Matrix MTP

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'The version of dotnet to use X.X.X'
        required: true
        type: string
      test-project-path:
        description: 'The path to the test project'
        required: true
        type: string

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Clean
        run: dotnet clean ${{ inputs.test-project-path }} -c ${{ matrix.configuration }}

      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.test-project-path }}

      - name: Build
        run: dotnet build ${{ inputs.test-project-path }} -c ${{ matrix.configuration }} --no-restore

      - name: Run Unit Tests
        # This is using dotnet run instead of test (Microsoft Testing Platform)
        run: dotnet run --project ${{ inputs.test-project-path }} --configuration ${{ matrix.configuration }}